netmaker_base_domain: a.b.c
netmaker_root_dir: /root/netmaker-compose
netmaker_server_public_ip: 127.0.0.1
netmaker_image_version: 0.18.6
netmaker_caddy_image_version: 2.6.2
coredns_image_version: 1.10.1
netmaker_acme_email: cicd.automation@modusbox.com
netmaker_mq_pw: crazypassword
netmaker_master_key: crazypassword
netmaker_admin_password: crazypassword
netmaker_admin_username: nmaker-admin
enable_oauth: false
netmaker_oidc_issuer: https://gitlab.com
netmaker_oidc_client_id: clientid
netmaker_oidc_client_secret: crazysecret
netmaker_enrollment_key_list_file_location: /tmp/keylist.json
netmaker_control_network_address_cidr_start: 10.20.30.0/24
netmaker_networks:
  - network_name: cntrlctr
    node_keys: 
      - ops
  - network_name: dev
    node_keys:
      - k8s
      - cc-svcs